version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27016:27017"
    # volumes:
    #   - "mongodata:/data/db"
    # networks:
    #   - network1
  
  go-app:
    restart: on-failure
    build: .
    ports:
      - "8000:8000"
    # depends_on:
    #     - mongodb
    # links:
    #     - mongodb
    # networks:
    #     - network1    
   
# volumes:
#    mongodata:

# networks:
#    network1:
#     driver: bridge